CREATE TABLE IF NOT EXISTS traffic_data (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp TIMESTAMP NOT NULL,
    car_count INTEGER NOT NULL CHECK (car_count >= 0),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_traffic_data_timestamp UNIQUE (timestamp)
);

CREATE INDEX IF NOT EXISTS idx_traffic_data_created_at ON traffic_data(created_at);
